Fix builds when using --config=asan.
Updating to a newer Oak version pulled in a newer rustc nightly,
enabling linking with lld. Since rules_rust doesn't (currently) include
gcc-ld in the sysroot, this caused build errors:

> error: the self-contained linker was requested, but it wasn't found in
> the target's sysroot, or in rustc's sysroot

It's unclear why builds didn't fail when using a gcc toolchain.

Change-Id: I2ddcf10325852bb7fb16f8cfd734ddde1b53bcd6