Pass `--locked` to `cargo build`  to ensure reproducibility.
Our current setup would allow updates to Cargo.toml to creep into
changes without corresponding updates to Cargo.lock, which in turn could
lead to non-reproducible builds if each build subsequently causes the
Cargo.lock file to be updated with a (potentially different each time)
version of a dep.

Passing `--locked` ensures that builds will fail in such cases, which
will allow us to catch those situations before submissions. Presubmits
will fail with an error like the following:

```
error: the lock file /workspace/Cargo.lock needs to be updated but
--locked was passed to prevent this
```

Change-Id: Ic33ca20a473a4634819f2eeedc040a5f7b71819d