Bring `containers/willow` up to Rust 2024, recent CFC, FCP, Oak etc.
This is similar to recent changes made in most other containers &
modules in CFC but which weren't applied to the willow container yet.

- Update to Rust 2024 edition and a rust compiler from 2026-04-11.
- Depend on the root CFC module via a local_path_override rule to get
  updates by default as soon as they land in shared code in that module.
  (If changes in the root module break code in `containers/willow` in
  ways that are not trivially patchable we can always fall back to
  pinning to a specific commit again, temporarily).
- Depend on a recent FCP version.
- Update to a recent Oak version by bringing the patches that `kms/`
  uses into this module as well.
- Remove `-Clink-self-contained=no` from the .bazelrc file since we
  don't need this in other Rust/C++-mixing containers (anymore?), for
  increased consistency across containers.
- Remove the `ubsan`-specific `-Wl,--allow-shlib-undefined` linkopt from
  .bazelrc since it also doesn't seem necessary anymore.
- Updating the protobuf patch to backport
  https://github.com/protocolbuffers/protobuf/commit/d1d263a82795423ee201b8b451d98e3fe324d621
  to make sure the a v2 of the `syn` crate is chosen and compiled with
  the right features that protobuf needs.
- Update various formatting and linter errors as a result of the above
  changes (incl. removing unused `#[feature(never_type)]` annotations.
- Fix one test's linker stage by marking it `linkstatic = True`. Without
  this the test failed to compile with `undefined reference to
  __rdl_alloc` errors.

Change-Id: I3ca5b4ea94495f5a5bdac1aba61f444e61982b68